version: '3.8'

services:
  flask-chat:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=your-secret-key-here
    volumes:
      - ./src/static/uploads:/app/src/static/uploads
      - ./src/database:/app/src/database
    restart: unless-stopped
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  uploads:
  database:

